import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from './component/Header'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "AI_ChatBot",
  description: "Generated by Muhammad Bilal Hussain",
  icons: "/public/b.png"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/public/b.png" sizes="32x32" type="image/png" />
        {/* <link rel="icon" href="https://your-website.com/b.png" sizes="32x32" /> */}
      </head>
      <body
        className={`bg-black ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
